######## Application Access Point ########

server:
    address: localhost
    port: 8080
    #contextPath: /

management:
    port: 8081
    #contextPath: /manage


######## Database Access Point ########

spring.datasource:
    url: jdbc:mysql://localhost:3306/java_jpa_test
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  output:
  ansi:
      enabled: DETECT
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
